version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#commands:
  # mysql -u root -p
    # when creating or logging in to database from application we get following error
    # Access denied for user 'root'@'192.168.65.1' (using password: YES) -> wrong password


  #  spring.datasource.url=jdbc:mysql://localhost:3307/wikimedia_db
  #  spring.datasource.username=root
  #  spring.datasource.password=pass
    # Access denied for user 'root'@'192.168.65.1' (using password: YES)

#but
  # user mannually mentiond users:
    # mysql -u prabidhi -p
    # password : pass


  database:
      image: mysql:latest
      container_name: mysql
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: prabidhi
        MYSQL_PASSWORD: pass
        MYSQL_DATABASE: prabidhi_db
      volumes:
        - ./db-dump:/docker-entrypoint-initdb.d

